import { Game } from '../models/Game';
import { Move } from '../models/Move';
import { Square } from './Square';
import { Piece } from '../models/Piece';
import { Pawn } from '../models/pieces/Pawn';
import { Knight } from '../models/pieces/Knight';
import { Bishop } from '../models/pieces/Bishop';
import { Rook } from '../models/pieces/Rook';
import { Queen } from '../models/pieces/Queen';
import { King } from '../models/pieces/King';

/**
 * Parses and formats chess moves in standard algebraic notation
 * 
 * Supported notation:
 * - Pawn moves: e4, d5
 * - Piece moves: Nf3, Bc4, Qd4
 * - Captures: exd5, Nxf6
 * - Castling: O-O (kingside), O-O-O (queenside)
 * - Disambiguation: Nbd7, R1a3, Qh4e1
 * - Check/Checkmate: +, #
 */
export class AlgebraicNotationParser {
  private game: Game;

  constructor(game: Game) {
    this.game = game;
  }

  /**
   * Parses algebraic notation and returns the corresponding Move
   * @param notation - Standard algebraic notation (e.g., "e4", "Nf3", "O-O")
   * @returns Move object
   * @throws Error if notation is invalid or move is illegal
   */
  parse(notation: string): Move {
    // Remove whitespace and check/checkmate markers for parsing
    const cleanNotation = notation.trim().replace(/[+#]$/, '');

    // Handle castling
    if (cleanNotation === 'O-O' || cleanNotation === '0-0') {
      return this.parseCastling(true);
    }
    if (cleanNotation === 'O-O-O' || cleanNotation === '0-0-0') {
      return this.parseCastling(false);
    }

    // Parse regular move
    const parseResult = this.parseNotation(cleanNotation);
    
    // Find the piece that can make this move
    const piece = this.findPiece(
      parseResult.pieceType,
      parseResult.toSquare,
      parseResult.isCapture,
      parseResult.fromFile,
      parseResult.fromRank
    );

    if (!piece) {
      throw new Error(`No ${parseResult.pieceType || 'pawn'} can move to ${parseResult.toSquare.notation}`);
    }

    // Verify the move is legal
    const move = new Move(piece.square, parseResult.toSquare, this.game.getBoard());
    const legalMoves = this.game.getBoard().getLegalMoves(piece);
    
    if (!legalMoves.some(m => m.equals(move))) {
      throw new Error(`Illegal move: ${notation}`);
    }

    return move;
  }

  /**
   * Formats a Move object into algebraic notation
   */
  format(move: Move): string {
    // Use the notation already generated by the Move class
    return move.getNotation();
  }

  /**
   * Parses a notation string into its components
   */
  private parseNotation(notation: string): {
    pieceType?: typeof Piece;
    toSquare: Square;
    isCapture: boolean;
    fromFile?: number;
    fromRank?: number;
  } {
    let pieceType: typeof Piece | undefined;
    let isCapture = notation.includes('x');
    let fromFile: number | undefined;
    let fromRank: number | undefined;
    let toSquare: Square;

    // Remove 'x' for easier parsing
    const withoutCapture = notation.replace('x', '');

    // Determine piece type
    const firstChar = withoutCapture[0];
    if (['N', 'B', 'R', 'Q', 'K'].includes(firstChar)) {
      pieceType = this.getPieceClass(firstChar);
      
      // Parse remainder for disambiguation and destination
      const remainder = withoutCapture.slice(1);
      const result = this.parseDestinationAndDisambiguation(remainder);
      toSquare = result.toSquare;
      fromFile = result.fromFile;
      fromRank = result.fromRank;
    } else {
      // Pawn move
      pieceType = undefined; // Pawns don't have a piece symbol
      
      if (withoutCapture.length === 2) {
        // Simple pawn move: e4
        toSquare = new Square(withoutCapture);
      } else if (withoutCapture.length === 3) {
        // Pawn capture with file disambiguation: exd5
        fromFile = Square.toCoordinates(withoutCapture[0] + '1').file;
        toSquare = new Square(withoutCapture.slice(1));
      } else {
        throw new Error(`Invalid pawn notation: ${notation}`);
      }
    }

    return { pieceType, toSquare, isCapture, fromFile, fromRank };
  }

  /**
   * Parses destination square and disambiguation info
   */
  private parseDestinationAndDisambiguation(str: string): {
    toSquare: Square;
    fromFile?: number;
    fromRank?: number;
  } {
    // Last 2 chars are always the destination square
    if (str.length < 2) {
      throw new Error('Invalid notation');
    }

    const toSquare = new Square(str.slice(-2));
    const disambiguation = str.slice(0, -2);

    let fromFile: number | undefined;
    let fromRank: number | undefined;

    if (disambiguation.length === 1) {
      // Single char: could be file (a-h) or rank (1-8)
      if (disambiguation.match(/[a-h]/)) {
        fromFile = Square.toCoordinates(disambiguation + '1').file;
      } else if (disambiguation.match(/[1-8]/)) {
        fromRank = parseInt(disambiguation);
      }
    } else if (disambiguation.length === 2) {
      // Full square disambiguation: e.g., Qh4e1
      const disambigSquare = new Square(disambiguation);
      fromFile = disambigSquare.file;
      fromRank = disambigSquare.rank;
    }

    return { toSquare, fromFile, fromRank };
  }

  /**
   * Finds the piece that can make the specified move
   */
  private findPiece(
    pieceType: typeof Piece | undefined,
    toSquare: Square,
    isCapture: boolean,
    fromFile?: number,
    fromRank?: number
  ): Piece | undefined {
    const currentPlayer = this.game.getCurrentPlayer();
    let candidates: Piece[];

    if (!pieceType) {
      // Pawn
      candidates = this.game.getBoard().getPiecesByClass(Pawn, currentPlayer);
    } else {
      candidates = this.game.getBoard().getPiecesByColor(currentPlayer)
        .filter(p => p instanceof pieceType);
    }

    // Filter by disambiguation
    if (fromFile !== undefined) {
      candidates = candidates.filter(p => p.square.file === fromFile);
    }
    if (fromRank !== undefined) {
      candidates = candidates.filter(p => p.square.rank === fromRank);
    }

    // Find piece that can legally move to the destination
    const validPieces = candidates.filter(piece => {
      const legalMoves = this.game.getBoard().getLegalMoves(piece);
      return legalMoves.some(move => move.to.equals(toSquare));
    });

    if (validPieces.length === 0) {
      return undefined;
    }

    if (validPieces.length > 1) {
      throw new Error(`Ambiguous move - multiple pieces can move to ${toSquare.notation}`);
    }

    return validPieces[0];
  }

  /**
   * Handles castling moves
   */
  private parseCastling(kingside: boolean): Move {
    const currentPlayer = this.game.getCurrentPlayer();
    const rank = currentPlayer === 'white' ? 1 : 8;
    
    const fromSquare = new Square({ file: 5, rank }); // e1 or e8
    const toSquare = new Square({ file: kingside ? 7 : 3, rank }); // g1/g8 or c1/c8

    return new Move(fromSquare, toSquare, this.game.getBoard());
  }

  /**
   * Maps piece notation to piece class
   */
  private getPieceClass(symbol: string): typeof Piece {
    switch (symbol) {
      case 'N': return Knight;
      case 'B': return Bishop;
      case 'R': return Rook;
      case 'Q': return Queen;
      case 'K': return King;
      default: throw new Error(`Invalid piece symbol: ${symbol}`);
    }
  }
}
